name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.22.x"

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push API
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/api.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/stratoq-api:${{ github.ref_name }}

      - name: Build & push Worker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/worker.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/stratoq-worker:${{ github.ref_name }}

      - name: Build & push Scheduler
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/scheduler.Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/stratoq-scheduler:${{ github.ref_name }}
